FROM golang:1.26-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /tiny-controller ./cmd
FROM gcr.io/distroless/static:nonroot
COPY --from=build /tiny-controller /tiny-controller
ENTRYPOINT ["/tiny-controller"]
